on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
      
      - name: NPM Install
        run: npm install

      - name: Lint
        run: ./node_modules/.bin/tslint -c tslint.json src/**/*.ts

      - name: Build
        run: ./node_modules/.bin/tsc
